### ISSUE TITLE
It is not possible to select the timeframe for events

### ISSUE THREAD

**Issue by compgeniuses** [pluginsGLPI/advancedplanning#1]
When a certain Date is selected, and the 
New item - Reminder is opened.
--
There is no option or ability to select timeframe, thereby assuming this is a full day event.

**Comment by cedric-anne** [comment]
Hi,

This has nothing to do with this plugin.
It seems to be related to a core GLPI feature. Please open a bug on https://github.com/glpi-project/glpi and give more details if you want someone take a look at your issue.

Regards
