### ISSUE TITLE
Plugin installed but doesn't Work 

### ISSUE THREAD

**Issue by Ernander** [pluginsGLPI/advancedplanning#2]
I am using a GLPI 9.4.5 and when I've enabled this one it didin't work or appear.

![image](https://user-images.githubusercontent.com/18518448/85431978-a51b4a00-b558-11ea-938e-e5dc03127ed0.png)

It stills in a normal way:

![image](https://user-images.githubusercontent.com/18518448/85432092-d3992500-b558-11ea-85f0-56965101c0df.png)

**Comment by cedric-anne** [comment]
Hi,

This feature is only available on GLPI 9.5.

Regards
